ROOM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import AccountIndexView
from roomapp.views import RoomIndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AccountIndexView.as_view(), name='index'),

    path('test/', RoomIndexView.as_view(), name='roomlist'),

    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('boards/', include('boardapp.urls')),
    path('rooms/', include('roomapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('reviews/', include('reviewapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boardapp/urls.py
from django.urls import path

from boardapp.views import BoardCreateView, BoardUpdateView, BoardDetailView, BoardDeleteView, BoardListView

app_name = "boardapp"

urlpatterns = [
    path('create/', BoardCreateView.as_view(), name='create'),
    path('update/<int:pk>', BoardUpdateView.as_view(), name='update'),
    path('detail/<int:pk>', BoardDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', BoardDeleteView.as_view(), name='delete'),

    path('list/', BoardListView.as_view(), name='list'),
]

boardapp/models.py
import re

from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Board(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='board', null=True)
    title = models.CharField(max_length=200, null=True)
    content = RichTextField(null=True)
    created_at = models.DateField(auto_now_add=True, null=True)

    def summary(self):
        remove_tags = re.compile('<.*?>')
        if len(re.sub(remove_tags, '', self.content)) > 100:
            return re.sub(remove_tags, '', self.content)[:100] + ' ...'
        return re.sub(remove_tags, '', self.content)


commentapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from boardapp.models import Board


class Comment(models.Model):
    board = models.ForeignKey(Board, on_delete=models.SET_NULL, null=True, related_name='comment')
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='comment')

    content = models.TextField(null=False)

    created_at = models.DateTimeField(auto_now=True)

reviewapp/models.py

import re

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Review(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='review', null=True)
    room = models.CharField(max_length=20, null=True)
    content = models.CharField(max_length=500, null=True)

    rate_choice = [('5점', '5점'), ('4점', '4점'), ('3점', '3점'), ('2점', '2점'),
                   ('1점', '1점')]
    rate = models.CharField(max_length=10, choices=rate_choice, null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

    def summary(self):
        remove_tags = re.compile('<.*?>')
        if len(re.sub(remove_tags, '', self.content)) > 100:
            return re.sub(remove_tags, '', self.content)[:100] + ' ...'
        return re.sub(remove_tags, '', self.content)

boardapp/forms.py
from django import forms
from django.forms import ModelForm

from boardapp import models
from boardapp.models import Board


class BoardCreationForm(ModelForm):
    #type = forms.ModelChoiceField(queryset=Board.objects.all(), required=False)

    class Meta:
        model = Board
        fields = ['title', 'content']

boardapp/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, ListView, DetailView, UpdateView
from django.views.generic.edit import FormMixin

from boardapp.decorators import board_ownership_required, LoginRequired
from boardapp.forms import BoardCreationForm
from boardapp.models import Board
from commentapp.forms import CommentCreationForm
from commentapp.models import Comment


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class BoardCreateView(CreateView):
    model = Board
    form_class = BoardCreationForm
    template_name = 'boardapp/create.html'

    def form_valid(self, form):
        temp_board = form.save(commit=False)
        temp_board.writer = self.request.user
        temp_board.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('boardapp:detail', kwargs={'pk': self.object.pk})



class BoardDetailView(LoginRequired, DetailView, FormMixin):
    login_url = '/accounts/login/'
    model = Board
    form_class = CommentCreationForm
    context_object_name = 'target_post'
    template_name = 'boardapp/detail.html'

    def get_context_data(self, **kwargs):
        comment_list = Comment.objects.filter(board=self.object.pk).order_by('-created_at')
        # if user.is_authenticated: #로그인 했는가?
        # join = Join.objects.filter(user=user, project=project)
        # object_list = Post.object(project=self.get_object())
        return super(BoardDetailView, self).get_context_data(comment_list=comment_list, **kwargs)


@method_decorator(board_ownership_required, 'get')
@method_decorator(board_ownership_required, 'post')
class BoardUpdateView(UpdateView):
    model = Board
    context_object_name = 'target_post'
    form_class = BoardCreationForm
    template_name = 'boardapp/update.html'

    def get_success_url(self):
        return reverse('boardapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(board_ownership_required, 'get')
@method_decorator(board_ownership_required, 'post')
class BoardDeleteView(DeleteView):
    model = Board
    context_object_name = 'target_post'
    success_url = reverse_lazy('boardapp:list')
    template_name = 'boardapp/delete.html'


class BoardListView(LoginRequired, ListView):
    login_url = '/accounts/login/'
    model = Board
    context_object_name = 'post_list'
    # ordering = ['-id']
    template_name = 'boardapp/list.html'

    def get_queryset(self):
        all_list = Board.objects.filter(writer__room=self.request.user.room).order_by('-id')

        page = int(self.request.GET.get('page', 1))
        paginator = Paginator(all_list, 4)
        queryset = paginator.get_page(page)

        return queryset


boardapp/templates/boardapp/create.html
{% extends 'base.html' %}
{% block content %}


<div style="margin: 1.8rem">
<div class="elements-section-headline-wrap yellow">
    <div id="Hero" class="section detail">
        <div class="blog1-headline-wrap detail_page">
            <div class="size3-text post">자취방 관련 글 남기기<br></div>
        </div>
    </div>
</div>


<div class="section" style="margin: 1.8rem">
    <div class="w-form">
        <form action="{% url 'boardapp:create' %}" method="post" enctype="multipart/form-data" id="email-form"
              name="email-form" data-name="Email Form">
            {% csrf_token %}
            {{ form.media }}
            <div>
                <label for="email-2">제목 : </label>
                <input type="text" maxlength="256" name="title" data-name="Title" placeholder="">
            </div>
            <div>
                <label for="email-2">글 내용</label><br>
                <div class="django-ckeditor-widget" data-field-id="id_content" style="display: inline-block;">
                          <textarea class="form-control" cols="40" id="id_content" name="content" placeholder="Content"
                                    rows="10"
                                    title="" required data-processed="0"
                                    data-config='{"skin": "moono-lisa", "toolbar_Basic": [["Source", "-", "Bold", "Italic"]], "toolbar_Full": [["Styles", "Format", "Bold", "Italic", "Underline", "Strike", "SpellChecker", "Undo", "Redo"], ["Link", "Unlink", "Anchor"], ["Image", "Flash", "Table", "HorizontalRule"], ["TextColor", "BGColor"], ["Smiley", "SpecialChar"], ["Source"]], "toolbar": "full", "height": 291, "width": 835, "filebrowserWindowWidth": 940, "filebrowserWindowHeight": 725, "extraPlugins": "codesnippet", "codeSnippet_theme": "monokai_sublime", "language": "ko-kr"}'
                                    data-external-plugin-resources="[]" data-id="id_content"
                                    data-type="ckeditortype"></textarea>
                </div>
            </div>
            <div>
                <input type="submit" value="제출하기">
            </div>

        </form>
    </div>
</div>
</div>
{% endblock %}

boardapp/templates/boardapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Delete Post : {{ target_post.title }}</h4>
    </div>
    <form action="{% url 'boardapp:delete' pk=target_post.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

boardapp/templates/boardapp/detail.html
{% extends 'base.html' %}
{% block content %}


<div class="feature col" style="margin: 1.8rem">
    <h2>제목: {{target_post.title}}</h2>
    글쓴이 : {{target_post.writer}}<br>
    내용 : {{target_post.content | safe}}<br>
    <a href="{% url 'boardapp:list' %}">목록</a>
</div>
<!--목록 가기-->



<div class="feature col" style="margin: 1.8rem">
<!--   댓글 쓰기 -->
{% include 'commentapp/create.html' with board=target_post %}<br>
Comment<br>
</div>

<div class="feature col" style="margin: 1.8rem">
<!--    댓글 리스트 -->
{% for comment in comment_list %}
{% include 'commentapp/detail.html' %}
{% endfor %}
</div>
{% endblock %}

boardapp/templates/boardapp/list.html
{% extends 'base.html' %}
{% block content %}

        <div style="margin: 1.8rem">
        <h4> ■ 자취방 커뮤니티</h4>
        <button style="width: 8rem; height: 3.0rem;"> <a href="{% url 'boardapp:create' %}"><div>글쓰기</div></a></button>
        </div>
        {% for post in post_list %}
        <div class="feature col" style="margin: 1.8rem">
            <h2 style="color: black">{{post.title}}</h2>
            <p style="color: gray; width: 45rem">{% include 'user_data.html' %}</p>
            <p style="color: gray; width: 45rem">{{post.content}}</p>
            <a href="{% url 'boardapp:detail' pk=post.pk%}" class="icon-link" style="float:right; width: 70rem">
                ▶ 게시물 상세보기
                <svg class="bi" width="1em" height="1em"><use xlink:href="#chevron-right"></use></svg>
            </a>
        </div>
        <br>
        {% endfor %}
<br><br>
{% include 'page.html' %}
{% endblock %}

boardapp/templates/boardapp/update.html
{% extends 'base.html' %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Post Update</h4>
    </div>
    <form action="{% url 'boardapp:update' pk=target_post.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form }}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}