ROOM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import AccountIndexView
from roomapp.views import RoomIndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AccountIndexView.as_view(), name='index'),

    path('test/', RoomIndexView.as_view(), name='roomlist'),

    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('boards/', include('boardapp.urls')),
    path('rooms/', include('roomapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('reviews/', include('reviewapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviewapp/urls.py

from django.urls import path

from reviewapp.views import ReviewCreateView, ReviewUpdateView, ReviewDetailView, ReviewDeleteView, ReviewListView

app_name = "reviewapp"

urlpatterns = [
    path('create/', ReviewCreateView.as_view(), name='create'),
    path('update/<int:pk>', ReviewUpdateView.as_view(), name='update'),
    path('detail/<int:pk>', ReviewDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', ReviewDeleteView.as_view(), name='delete'),

    path('list/', ReviewListView.as_view(), name='list'),
]

reviewapp/models.py

import re

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Review(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='review', null=True)
    room = models.CharField(max_length=20, null=True)
    content = models.CharField(max_length=500, null=True)

    rate_choice = [('5점', '5점'), ('4점', '4점'), ('3점', '3점'), ('2점', '2점'),
                   ('1점', '1점')]
    rate = models.CharField(max_length=10, choices=rate_choice, null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

    def summary(self):
        remove_tags = re.compile('<.*?>')
        if len(re.sub(remove_tags, '', self.content)) > 100:
            return re.sub(remove_tags, '', self.content)[:100] + ' ...'
        return re.sub(remove_tags, '', self.content)

reviewapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import FormMixin, UpdateView, DeleteView

from commentapp.forms import CommentCreationForm
from commentapp.models import Comment
from reviewapp.decorators import LoginRequired, review_ownership_required
from reviewapp.form import ReviewCreationForm
from reviewapp.models import Review


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ReviewCreateView(CreateView):
    model = Review
    form_class = ReviewCreationForm
    template_name = 'reviewapp/create.html'

    def form_valid(self, form):
        temp_review = form.save(commit=False)
        temp_review.writer = self.request.user
        temp_review.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        return super(ReviewCreateView, self).get_context_data(user=self.request.user, **kwargs)
    def get_success_url(self):
        return reverse('reviewapp:detail', kwargs={'pk': self.object.pk})


class ReviewDetailView(LoginRequired, DetailView):
    login_url = '/accounts/login/'
    model = Review
    form_class = CommentCreationForm
    context_object_name = 'target_post'
    template_name = 'reviewapp/detail.html'


@method_decorator(review_ownership_required, 'get')
@method_decorator(review_ownership_required, 'post')
class ReviewUpdateView(UpdateView):
    model = Review
    context_object_name = 'target_post'
    form_class = ReviewCreationForm
    template_name = 'reviewapp/update.html'

    def get_success_url(self):
        return reverse('reviewapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(review_ownership_required, 'get')
@method_decorator(review_ownership_required, 'post')
class ReviewDeleteView(DeleteView):
    model = Review
    context_object_name = 'target_post'
    success_url = reverse_lazy('reviewapp:list')
    template_name = 'reviewapp/delete.html'


class ReviewListView(LoginRequired, ListView):
    login_url = '/accounts/login/'
    model = Review
    context_object_name = 'post_list'
    # ordering = ['-id']
    template_name = 'reviewapp/list.html'

    def get_queryset(self):
        all_list = Review.objects.filter().order_by('-id')

        page = int(self.request.GET.get('page', 1))
        paginator = Paginator(all_list, 4)
        queryset = paginator.get_page(page)

        return queryset

reviewapp/templates/reviewapp/create.html
{% extends 'base.html' %}
{% block content %}


<div class="elements-section-headline-wrap yellow">
    <div id="Hero" class="section detail">
        <div class="blog1-headline-wrap detail_page">
            <div class="size3-text post">Post<br></div>
        </div>
    </div>
</div>


<div class="section">
    <div class="w-form">
        <form action="{% url 'reviewapp:create' %}" method="post" enctype="multipart/form-data" id="email-form"
              name="email-form" data-name="Email Form">
            {% csrf_token %}
            <tr><th><label for="id_type">별점:</label></th><td><select name="type" required id="id_type">
          <option value="" selected>---------</option>

          <option value="5점">5점</option>

          <option value="4점">4점</option>

          <option value="3점">3점</option>

          <option value="2점">2점</option>

          <option value="1점">1점</option>

        </select></td></tr>
        <tr><th><label for="id_room">지냈던 자취방 : </label></th><td><input type="text" value="{{user.room.name}}" name="room" maxlength="20" required id="id_room" readonly></td></tr>
        <tr><th><label for="id_content">리뷰내용 : </label></th><td><input type="text" name="content" maxlength="500" required id="id_content"></td></tr>
            <input type="submit" value="제출">
        </form>
    </div>


</div>
{% endblock %}

reviewapp/templates/reviewapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Delete Post : {{ target_post.title }}</h4>
    </div>
    <form action="{% url 'reviewapp:delete' pk=target_post.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

reviewapp/templates/reviewapp/detail.html
{% extends 'base.html' %}
{% block content %}


<div class="feature col" style="margin: 1.8rem">
    <h2 style="color: black">{{target_post.writer}} 의 리뷰</h2>
    <h2 style="color: black">원룸 : {{target_post.room}}</h2>
            <h2 style="color: black">별점 :
            {% if target_post.rate == '5점' %}
            ★★★★★
            {% elif target_post.rate == '4점' %}
            ★★★★☆
            {% elif target_post.rate == 3 %}
            ★★★☆☆
            {% elif target_post.rate == 2 %}
            ★★☆☆☆
            {% else %}
            ★☆☆☆☆
            {% endif %}</h2>
            <div>
                <h3>내용 : {{target_post.content | safe}}</h3>
            </div>

        </div><br>

<!--목록 가기-->
<a href="{% url 'reviewapp:list' %}">목록</a>

{% endblock %}

reviewapp/templates/reviewapp/list.html
{% extends 'base.html' %}
{% block content %}

        <div style="margin: 1.8rem">
            <h4> ■ 자취방 리뷰</h4>
            <button style="width: 8rem; height: 3.0rem;"> <a href="{% url 'reviewapp:create' %}"><div>리뷰쓰기</div></a></button>
        </div>
        {% for post in post_list %}
        <div class="feature col" style="margin: 1.8rem">
            <h2 style="color: black">{{post.room}}</h2>
            <p style="color: gray; width: 45rem">요약 : {{ post.summary | safe }}</p>
            <p style="color: gray; width: 45rem">{{post.content}}</p>
            <a href="{% url 'reviewapp:detail' pk=post.pk%}" class="icon-link" style="float:right; width: 70rem">
                ▶ 원룸 정보 상세보기
                <svg class="bi" width="1em" height="1em"><use xlink:href="#chevron-right"></use></svg>
            </a>
        </div>
        <br>
        {% endfor %}
    </div>
</div>
<br><br>
{% include 'page.html' %}
{% endblock %}

reviewapp/templates/reviewapp/update.html
{% extends 'base.html' %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Post Update</h4>
    </div>
    <form action="{% url 'reviewapp:update' pk=target_post.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form }}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}