ROOM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import AccountIndexView
from roomapp.views import RoomIndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AccountIndexView.as_view(), name='index'),

    path('test/', RoomIndexView.as_view(), name='roomlist'),

    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('boards/', include('boardapp.urls')),
    path('rooms/', include('roomapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('reviews/', include('reviewapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

boardapp/urls.py
from django.urls import path

from boardapp.views import BoardCreateView, BoardUpdateView, BoardDetailView, BoardDeleteView, BoardListView

app_name = "boardapp"

urlpatterns = [
    path('create/', BoardCreateView.as_view(), name='create'),
    path('update/<int:pk>', BoardUpdateView.as_view(), name='update'),
    path('detail/<int:pk>', BoardDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', BoardDeleteView.as_view(), name='delete'),

    path('list/', BoardListView.as_view(), name='list'),
]

reviewapp/urls.py

from django.urls import path

from reviewapp.views import ReviewCreateView, ReviewUpdateView, ReviewDetailView, ReviewDeleteView, ReviewListView

app_name = "reviewapp"

urlpatterns = [
    path('create/', ReviewCreateView.as_view(), name='create'),
    path('update/<int:pk>', ReviewUpdateView.as_view(), name='update'),
    path('detail/<int:pk>', ReviewDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', ReviewDeleteView.as_view(), name='delete'),

    path('list/', ReviewListView.as_view(), name='list'),
]

roomapp/urls.py
from django.urls import path

from roomapp.views import RoomCreateView, RoomUpdateView, RoomIndexView

app_name = "roomapp"

urlpatterns = [
    path('create/', RoomCreateView.as_view(), name='create'),
    path('update/<int:pk>', RoomUpdateView.as_view(), name='update'),
    path('list/', RoomIndexView.as_view(), name='list'),
]

templates/base.html

<!DOCTYPE html>

<html>
    {% include 'head.html' %}
    <body>
        <div style="flex: 1">
            {% include 'header.html' %}
        </div>

        <div>
            <hr><hr>
            {% block content %}
            {% endblock %}
            <hr><hr>
        </div>

        <div style="margin-top: 1.5rem; flex: 1">
            {% include 'footer.html' %}
        </div>
    </body>
</html>

templates/base_main.html
<!DOCTYPE html>

<html>
    {% include 'head.html' %}
    <body>
        <div style="flex: 1">
            {% include 'header.html' %}
        </div>

        <div style="text-align: center; margin: 2rem">
            <img src="https://www.acon3d.com/data/goods/20/05/22/1000001763/1000001763_detail_083.PNG" style="width:400; height:400">
            <h2>당신이 원하는 자취방</h2>
            <h1>방을 구한다 ! 방 구 방 구</h1>
        </div>

        <div style="margin-top: 1.5rem; flex: 1">
            {% include 'footer.html' %}
        </div>
    </body>
</html>

templates/error.html
{% extends 'base.html' %}
{% block content %}
<h4>Error</h4>

{% endblock %}

templates/footer.html
<div>
    <div style="text-align:center; font-size: 1.2rem">
        Developer 김범창 최준호 황유진
    </div>
    <div style="text-align:center">
        Copyrightⓒ 2021. UnderdogRevolution. All rights reserved.
    </div>
</div>

templates/head.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!--  GOOGLE MATERIAL ICONS  -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
</head>

templates/header.html
<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center">
            <div style="flex: 1">
                <a href="{% url 'index' %}" style="text-align:center;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="white" class="bi bi-wind"
                         viewBox="0 0 16 16">
                        <path d="M12.5 2A2.5 2.5 0 0 0 10 4.5a.5.5 0 0 1-1 0A3.5 3.5 0 1 1 12.5 8H.5a.5.5 0 0 1 0-1h12a2.5 2.5 0 0 0 0-5zm-7 1a1 1 0 0 0-1 1 .5.5 0 0 1-1 0 2 2 0 1 1 2 2h-5a.5.5 0 0 1 0-1h5a1 1 0 0 0 0-2zM0 9.5A.5.5 0 0 1 .5 9h10.042a3 3 0 1 1-3 3 .5.5 0 0 1 1 0 2 2 0 1 0 2-2H.5a.5.5 0 0 1-.5-.5z"/>
                    </svg>
                    <h1 style="color:white">방구방구</h1>
                </a>
            </div>
            <div style="flex: 2">
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">

                    {% if user.is_authenticated %}
                    <li><a href="{% url 'reviewapp:list' %}" class="nav-link px-2 text-white"><span>자취방 리뷰</span></a>
                    <li><a href="{% url 'roomapp:list' %}" class="nav-link px-2 text-white">자취방 목록</a></li>
                    <li><a href="{% url 'boardapp:list' %}" class="nav-link px-2 text-white">자취방 커뮤니티</a></li>
                    <li><a href="{% url 'accountapp:detail' pk=user.pk %}" class="nav-link px-2 text-white"><span>내정보</span></a></li>
                    <li><a href="{% url 'accountapp:logout' %}" class="nav-link px-2 text-white"><span>logout</span></a></li>
                    {% else %}
                    <a href="{% url 'accountapp:create' %}"
                       class="nav-link px-2 text-white"><span>SIGN IN</span></a></li>
                    <a href="{% url 'accountapp:login' %}" class="nav-link px-2 text-white"><span>LOGIN</span></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</header>

templates/not_profile.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h1>please make your profile</h1>
    <a href="{% url 'profileapp:create' %}">프로필 생성</a>
    <a onclick="history.go(-1)">
        <div>
                <div>Back</div>
        </div>
    </a>
</div>

{% endblock %}

templates/temp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>