ROOM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import AccountIndexView
from roomapp.views import RoomIndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AccountIndexView.as_view(), name='index'),

    path('test/', RoomIndexView.as_view(), name='roomlist'),

    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('boards/', include('boardapp.urls')),
    path('rooms/', include('roomapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('reviews/', include('reviewapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = "profileapp"

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

profileapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Profile(models.Model):
    #profile과 user객체를 1:1로 연결, on_delete:Profile과 연결된 User객체가없어질 때 행동, profile도 없어짐, 연관짓기 #request.user.profile
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    #media root 밑에 profile에 저장됨.
    # image = models.ImageField(upload_to='profile/', null=True)
    name = models.CharField(max_length=20, null=True)
    number = models.CharField(max_length=15, null=True)


profileapp/forms.py
from django.forms import ModelForm

from profileapp.models import Profile


class ProfileCreationForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'number']

profileapp/views.py
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView

from profileapp.decorators import profile_ownership_required
from profileapp.forms import ProfileCreationForm
from profileapp.models import Profile


class ProfileCreateView(CreateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    template_name = 'profileapp/create.html'

    def form_valid(self, form):
        temp_profile = form.save(commit=False)
        temp_profile.user = self.request.user
        temp_profile.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk':self.object.user.pk})


@method_decorator(profile_ownership_required, 'get')
@method_decorator(profile_ownership_required, 'post')
class ProfileUpdateView(UpdateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    template_name = 'profileapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk':self.object.user.pk})

profileapp/templates/profileapp/create.html
{% extends 'base.html' %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Profile Create</h4>
    </div>
    <form action="{% url 'profileapp:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <tr><th><label for="id_name">유저 이름:</label></th><td><input type="text" name="name" maxlength="20" required id="id_name"></td></tr><br>
        <tr><th><label for="id_number">휴대폰 번호:</label></th><td><input type="text" name="number" maxlength="15" required id="id_number"></td></tr>
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

profileapp/templates/profileapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Update Profile</h4>
    </div>
    <form action="{% url 'profileapp:update' pk=target_profile.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}